# Generated by Django 4.2.24 on 2025-09-30 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('discord_channel_name', models.CharField(max_length=255)),
                ('discord_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_split', models.BooleanField(default=False)),
                ('split_count', models.IntegerField(default=1)),
                ('file_extension', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='FilePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('discord_message_id', models.CharField(max_length=255)),
                ('part_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='storage.uploadedfile')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('uploaded_file', 'part_number')},
            },
        ),
    ]
